language: cpp
compiler:
  - gcc
install:
  - sudo apt-get -qq update || true
  - sudo apt-get -qq install python3
before_script:
  - sudo add-apt-repository ppa:vbernat/haproxy-1.5 -y
  - sudo apt-get update -qq || true
  - sudo apt-get install haproxy
script:
  - ./runtests
branches:
  only:
    - master
notifications:
  #irc:
    #channels:
      #- "chat.freenode.net#mwa"
    #template:
      #- "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
  email:
    recipients:
      - jkaluza@redhat.com
    on_success: always
    on_failure: always
