#!/usr/bin/env python
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Jan Kaluza <jkaluza at redhat dot com>
# Description: Converts webserver configuration from webconfig-spec JSON
# format to native HAProxy configuration format.

from __future__ import print_function
from urlparse import urlparse
import sys
import json
import os
import uuid
import StringIO

# For the tests, we want to use not random UUIDs, so switch
# to debug_uuid when running with --debug
debug_counter = 0
def debug_uuid():
    global debug_counter
    debug_counter += 1
    return "debug_" + str(debug_counter)

if len(sys.argv) == 4 and sys.argv[3] == "--debug":
    uuid.uuid1 = debug_uuid

def print_help():
    print("Usage:", sys.argv[0], "<config_file_or_directory> <output_directory>")

# Loads the config "c" and store it to internal configs storage "cfgs".
def load_config(cfgs, c):
    # The configs stored in Kubernetes/Openshift API-server can have their IDs.
    # We use the ID here as a name of the web application configured by the
    # config, so later when generating the httpd config, we can name it
    # according to web application configured by the config.
    if "id" in c:
        name = c["id"]
        name = name.replace("-","_")
    else:
        name = str(uuid.uuid1())

    # In case the ID is not unique and the config with this ID has been
    # already loaded, append UUID to it.
    if name in cfgs["webapps"]:
        name += str(uuid.uuid1())

    # For now we support also loading from "webconfig".
    # FIXME: This is not according to webconfig-spec. Micro-webapps confd.py has
    # to be fixed before removing this.
    if "webconfig" in c:
        cfgs["webapps"][name] = c["webconfig"]
    else:
        cfgs["webapps"][name] = c

    return cfgs

# Replaces %X% with value of X environment variable.
# Replaces %THIS_X% with value of app_name_X environment variable.
# FIXME: ^ Is this realy needed or beneficial?
def expand_variables(line, app_name):
    if line.startswith("%") and line.endswith("%"):
        env = line[1:-1]
        if env.startswith("THIS_"):
            env = env.replace("THIS_", app_name.upper() + "_")
        return os.getenv(env, "")

    ret = ""
    lst = line.split("%")
    for part in lst:
        env = part
        if env.startswith("THIS_"):
            env = env.replace("THIS_", app_name.upper() + "_")
        val = os.getenv(env, False)
        if val == False:
            ret += part + "%"
        else:
            ret = ret[:-1]
            ret += val
    return ret[:-1] # remove last %

# Returns two objects from "cfgs":
# - webapps_per_vhost - {vhost1:[app1_cfg, app2_cfg, ...], ...}
# - webapps_without_vhost - [app1_cfg, app2_cfg, ...]
def get_webapps_per_vhost(cfgs):
    webapps_per_vhost = {}
    webapps_without_vhost = []
    for app, app_cfg in cfgs["webapps"].items():
        # We would loss the app name, so store it under __name__ key.
        # FIXME: Maybe in the future we could create App class here.
        app_cfg["__name__"] = app
        if "virtualhost" in app_cfg:
            # virtualhost can contain variable, so at first try to expand it.
            # If it's empty after the expansion, append it to
            # webapp_without_vhost list.
            vhost = expand_variables(app_cfg["virtualhost"], app)
            if len(vhost) == 0:
                webapps_without_vhost.append(app_cfg)
            else:
                if not vhost in webapps_per_vhost:
                    webapps_per_vhost[vhost] = []
                webapps_per_vhost[vhost].append(app_cfg)
        else:
            webapps_without_vhost.append(app_cfg)
    
    return webapps_per_vhost, webapps_without_vhost

class HAProxyProxyGenerator:
    def __init__(self, parent):
        self.p = parent
        self.name = "proxy"

    # Returns address of proxy in protocol://address:port format.
    # Returns None if the address cannot be obtained or is not set
    # in the proxy_cfg.
    def get_address(self, proxy_cfg):
        ret = ""

        if "url" in proxy_cfg["proxy"]:
            url = urlparse(proxy_cfg["proxy"]["url"])

            ret = expand_variables(url.scheme, self.p.app_name)
            if len(ret) == 0:
                ret = "http://"
            else:
                ret += "://"

            hostname = url.hostname
            port = url.port
        else:
            return None

        # For Kubernetes/Openshift, we allow getting the address and port of
        # the backend from the APP_NAME_PORT environment variable.
        address_env = self.p.app_name.upper() + "_PORT"
        address = os.getenv(address_env, False)
        if address:
            url = urlparse(address)
            # If we are running in Kubernetes/Openshift, use the IP address,
            # because it's static per service. Otherwise use the hostname
            # (app_name) and port from _PORT.
            if os.getenv("KUBERNETES_SERVICE_PORT", False) != False:
                ret += url.netloc
            else:
                ret += self.p.app_name + ":" + str(url.port)
        else:
            # The APP_NAME_PORT variable is not set, so fallback to
            # proxy_hostname and proxy_port.
            ret += hostname + ":" + str(port)

        return ret

    def write_proxypass(self, proxy_cfg):
        address = self.get_address(proxy_cfg)
        if not address:
            return

        # Default values...
        if not "alias" in proxy_cfg["proxy"]:
            proxy_cfg["proxy"]["alias"] = ""

        # Get proxy_backend_alias or set it to "/" if not set.
        if "url" in proxy_cfg["proxy"]:
            url = urlparse(proxy_cfg["proxy"]["url"])
            backend_alias = url.path
        else:
            return
    
        parsed = urlparse(address)
        backend_alias = expand_variables(backend_alias, self.p.app_name)
        proxy_alias = expand_variables(proxy_cfg["proxy"]["alias"], self.p.app_name)

        # We include the trailing / in the following HAProxy commands.
        if backend_alias == "/":
            backend_alias = ""
        if proxy_alias == "/":
            proxy_alias = ""

        #self.p.write(self.p.backends, "http-request set-header Host {0}", parsed.hostname)
        self.p.write(self.p.backends, "reqirep  ^([^\\ :]*)\\ {0}/(.*)     \\1\\ {1}/\\2", proxy_alias, backend_alias)

        #self.p.write(self.p.backends, "acl hdr_location res.hdr(Location) -m found")
        #self.p.write(self.p.backends, "rspirep ^Location:\\ (https?://{0}(:[0-9]+)?)?({1}/.*) Location:\\ {2}/ if hdr_location", parsed.hostname, backend_alias, proxy_alias)
        self.p.write(self.p.backends, "rspirep ^(Location:)\\ http://([^/]*){0}/(.*)$    \\1\\ {1}/\\3".format(backend_alias, proxy_alias))

        self.p.write(self.p.backends, "server {0} {1}", str(uuid.uuid1()), address[address.find("//") + 2:])

    def handle(self, proxy_cfg):
        if not "proxy" in proxy_cfg:
            return True

        self.write_proxypass(proxy_cfg)
        return True

class HAProxyGenerator:
    def __init__(self, main, backends):
        self.frontend = main
        self.backends = backends
        self.app_name = ""
        self.vhost_name = ""
        self.nested_sections = ["main"]

        # Directive handlers must not call run_directive_handlers
        # or run_section_handlers.
        self.directive_handlers = []
        self.directive_handlers.append(HAProxyProxyGenerator(self))

        # Section handlers are supposed to do their stuff and call
        # run_directive_handlers or run_section_handlers
        self.section_handlers = []

    # Writes the data to output file, expands the variables, uses the proper
    # indentation.
    def write(self, where, data, *args):
        if len(data) != 0:
            if len(args) == 1:
                args = (expand_variables(args[0], self.app_name),)
                if len(args[0]) == 0:
                    return;
            line = (len(self.nested_sections) - 1) * 4 * " " + data.format(*args)
            line = expand_variables(line, self.app_name)
            where.write(line)
        where.write("\n")

    # Runs the handlers from the list "lst" with config "cfg".
    # When enable/disable list is set, only enabled and not disabled handler
    # (based on their names) will be run.
    def run_handlers(self, lst, cfg, enable, disable):
        for handler in lst:
            if len(disable) != 0 and handler.name in disable:
                continue
            if len(enable) != 0 and not handler.name in enable:
                continue
            if not handler.handle(cfg):
                return False
        return True

    def run_directive_handlers(self, cfg, enable = [], disable = []):
        return self.run_handlers(self.directive_handlers, cfg, enable, disable)

    def run_section_handlers(self, cfg, enable = [], disable = []):
        return self.run_handlers(self.section_handlers, cfg, enable, disable)

    def write_app_config(self, app_cfg, enable = [], disable = []):
        self.app_name = app_cfg["__name__"]
        self.run_directive_handlers(app_cfg, enable, disable)
        self.run_section_handlers(app_cfg, enable, disable)

    def write_vhost_config(self, vhost, vhost_cfg, ssl = False):
        self.vhost_name = vhost
        
        for cfg in vhost_cfg:
            if not "proxy" in cfg:
                cfg["proxy"] = {}
            if not "alias" in cfg["proxy"]:
                cfg["proxy"]["alias"] = ""

            self.nested_sections.insert(0, "global")
            alias = cfg["proxy"]["alias"]
            if alias == "/":
                alias = ""

            backend_host = "backend_host_" + str(uuid.uuid1())
            backend_path = "backend_path_" + str(uuid.uuid1())
            backend_name = "backend_" + str(uuid.uuid1())

            if len(sys.argv) == 4 and sys.argv[3] == "--debug":
                self.write(self.frontend, "acl {0} req.hdr(Host) {1}:9090", backend_host, vhost)
            else:
                self.write(self.frontend, "acl {0} req.hdr(Host) {1}", backend_host, vhost)

            if "redirects" in cfg and cfg["redirects"].items()[0][0] == "/":
                if len(sys.argv) == 4 and sys.argv[3] == "--debug":
                    self.write(self.frontend, "redirect prefix https://{0}:9443 if {1} !{{ ssl_fc }}", vhost, backend_host)
                else:
                    self.write(self.frontend, "redirect scheme https code 301 if {0} !{{ ssl_fc }}", backend_host)

            self.write(self.frontend, "acl {0} path_reg ^{1}$|^{1}/", backend_path, alias)
            self.write(self.frontend, "use_backend {0} if {1} {2}", backend_name, backend_host, backend_path)
            
            if "certificate" in cfg and "certificate_key" in cfg:
                self.write(self.frontend, "use_backend {0} if {1} {{ ssl_fc_sni {2} }}", backend_name, backend_path, vhost)

            self.nested_sections.pop(0)
            self.write(self.backends, "backend {0}", backend_name)
            self.nested_sections.insert(0, "virtualhost")

            self.write_app_config(cfg)
            self.nested_sections.pop(0)

def write_ssl_frontend(cfgs, outp):
    cert_dir = sys.argv[2][:sys.argv[2].rfind("/")] + "/certs"
    os.system("mkdir -p " + cert_dir)

    enable_ssl = False
    for vhost, vhost_cfg in cfgs.items():
        for cfg in vhost_cfg:
            if not "certificate" in cfg or not "certificate_key" in cfg:
                continue
            cert = cfg["certificate"]
            key = cfg["certificate_key"]
            pem_file = cert_dir + "/" + os.path.basename(cert) + ".pem"
            os.system("cat {0} {1} > {2}".format(cert, key, pem_file));
            enable_ssl = True

    if enable_ssl:
        if len(sys.argv) == 4 and sys.argv[3] == "--debug":
            outp.write("    bind *:9443 ssl crt " + cert_dir + "\n")
        else:
            outp.write("    bind *:443 ssl crt " + cert_dir + "\n")

def generate_config(inp, outp):
    cfgs = {"webapps":{}}
    if os.path.isdir(inp):
        for f in os.listdir(inp):
            if f.endswith(".json"):
                f = open(inp + "/" + f, "r")
                c = json.load(f)
                f.close()
                cfgs = load_config(cfgs, c)
    else:
        f = open(inp, "r")

        cfgs = json.load(f)
        f.close()

    port = 80
    if len(sys.argv) == 4 and sys.argv[3] == "--debug":
        port = 9090

    main = StringIO.StringIO()
    main.write("""global
    maxconn 4096
    node lb1
    spread-checks 5

defaults
    log     global
    mode    http
    # option  httplog
    option  dontlognull
    retries 3
    option redispatch
    maxconn 2000
    contimeout      5000
    clitimeout      50000
    srvtimeout      50000

frontend ft_global
    bind *:{0}
    mode http
""".format(port))

    backends = StringIO.StringIO()

    webapps_per_vhost, webapps_without_vhost = get_webapps_per_vhost(cfgs)

    write_ssl_frontend(webapps_per_vhost, main)

    for vhost, vhost_cfg in webapps_per_vhost.items():
        generator = HAProxyGenerator(main, backends)
        generator.write_vhost_config(vhost, vhost_cfg)

    out = open(outp, "w")
    out.write(main.getvalue())
    out.write(backends.getvalue())
    out.close()
    return 0

def main():
    if len(sys.argv) < 3:
        print_help()
        return 1

    return generate_config(sys.argv[1], sys.argv[2])

sys.exit(main())
